### web
server:
  port: 0


###logger
logging:
  config: classpath:logger/logback.xml
spring:
  profiles:
    active: local


watcher:
  botToken: "5361343175:AAGoLxFzG1m0Ppq"
  chatId: "-8759"
  addressList:
    - "0x0c1AE55"
    - "0x027b2B9"
    - "0x66b2Dbe"
    - "0xa4f120f"

